### ISSUE TITLE
Game crash upon entering Nexus's profile (lol)

### ISSUE THREAD

**Issue by banana-man95** [Jouca/BadgesAPI#1]
Not exactly sure whether it's your mod alone or a mod I have that's conflicting with yours, but if you enter Nexus's profile, it'll crash with an access violation.

Steps to reproduce:
1. Enter Geometry Dash, using BadgesAPI
2. Go to search bar
3. Type "Nexus"
4. Search for players
5. Enter Nexus profile
6. Crash after around 0.4 seconds
(If you don't end up crashing, it might be mod conflicts)

BetterCrashlogs generated crashlog if useful:

```
2024-09-06T23:41:53-0400
Quick, look over there! *runs away*

== Geode Information ==
- Working Directory: C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash
- Loader Version: v3.4.0 (Geometry Dash v2.206)
- Loader Commit: a533b5f
- Bindings Commit: de6a02b
- Installed Mods: 41 (Loaded: 39/39)
- Problems: 0

== Exception Information ==
- Thread Information: "Main" (ID: 64616)
- Thread Start Address: GeometryDash.exe+0x4A41C8 (<0x4a41c8>+0x0)
- Exception Code: EXCEPTION_ACCESS_VIOLATION (0xC0000005)
- Exception Address: libcocos2d.dll+0x7060 (cocos2d::CCArray::stringAtIndex+0x0)
- Exception Flags: 0x0
- Exception Parameters: 0x0, 0x38
- Access Violation Type: Read
- Access Violation Address: 0x00000038
- Protect: PAGE_NOACCESS (0x1)
- State: MEM_FREE (0x10000)
- Type: Unknown (0x0)

== Stack Trace ==
- libcocos2d.dll+0x7060 (cocos2d::CCArray::stringAtIndex+0x0)
- jouca.badgesapi.dll+0x61F9 (<0x5d80>+0x479)
- jouca.badgesapi.dll+0x591E (<0x5170>+0x7ae)
- 0x1D771094472+0x0
- GeometryDash.exe+0x3A21A2 (ProfilePage::onRequests+0xb2)
- 0x1D770C63872+0x0
- Geode.dll+0x36002E (ProfilePage::getUserInfoFinished+0x3e)
└ /home/runner/work/geode/geode/build/bindings/bindings/Geode/GeneratedSource.cpp:26888
- 0x1D770C63872+0x0
- GeometryDash.exe+0x154352 (<0x154200>+0x152)
- GeometryDash.exe+0x13EAF0 (GameLevelManager::handleIt+0x630)
- GeometryDash.exe+0x13E484 (GameLevelManager::ProcessHttpRequest+0x254)
- 0x1D77120B872+0x0
- cvolton.betterinfo.dll+0xF3F00
- cvolton.betterinfo.dll+0x26417 (<0x25b90>+0x887)
- 0x1D77120B872+0x0
- libExtensions.dll+0x1805A (cocos2d::extension::CCHttpClient::dispatchResponseCallbacks+0xaa)
- libcocos2d.dll+0xC0629 (cocos2d::CCTimer::update+0x69)
- libcocos2d.dll+0xC049B (cocos2d::CCScheduler::update+0x10b)
- 0x1D770C64472+0x0
- 0x1D770C64472+0x0
- 0x1D770C64472+0x0
- 0x1D770C64472+0x0
- absolllute.megahack.dll+0x164B15 (<0x164aa0>+0x75)
- 0x1D702FC24D2+0x0
- libcocos2d.dll+0xBC33B (<0xbc2c0>+0x7b)
- libcocos2d.dll+0x72CD2 (cocos2d::CCApplication::run+0x462)
- GeometryDash.exe+0x4A2D69 (<0x4a2ca6>+0xc3)
- Geode.dll+0x2453DA (gdMainHook+0x22a)
└ /home/runner/work/geode/geode/loader/src/platform/windows/main.cpp:167
- GeometryDash.exe+0x4A415A (__scrt_common_main_seh+0x106)
- KERNEL32.DLL+0x1257D (BaseThreadInitThunk+0x1d)
- ntdll.dll+0x5AF28 (RtlUserThreadStart+0x28)

== Register States ==
- RAX: 00000000 (0i | 0u)
- RBX: 00000000 (0i | 0u)
- RCX: 00000000 (0i | 0u)
- RDX: 00000000 (0i | 0u)
- RBP: 00000000 (0i | 0u)
- RSP: 304E93FA70 (&"")
- RDI: 00000000 (0i | 0u)
- RSI: 00000000 (0i | 0u)
- R8: 1D76D8821C0 (-> 0x1D76D880ED0 -> 0x16910002)
- R9: 00000001 (1i | 1u)
- R10: 00000003 (3i | 3u)
- R11: 304E93E090 (&"")
- R12: 00000000 (0i | 0u)
- R13: 00000000 (0i | 0u)
- R14: 00000000 (0i | 0u)
- R15: 00000000 (0i | 0u)
- RIP: 7FF9E6AAAF28 (ntdll.dll+0x5AF28 (RtlUserThreadStart+0x28))
- XMM0: 0000000000000000 0000000000000000 (0 | 0 | 0 | 0)
- XMM1: 676150656C69666F 7250207373616C63 (1.0640155e+24 | 1.1286538e+27 | 4.122375e+30 | 1.7859881e+31)
- XMM2: 65676150656C6966 6F7250207373616C (6.829136e+22 | 6.977642e+22 | 7.4992238e+28 | 1.9282594e+31)
- XMM3: 0000000000000000 40444999A0000000 (0 | 0 | 3.066992 | -1.0842022e-19)
- XMM4: 0000000000000000 4013CCCCE0000000 (0 | 0 | 2.3093748 | -3.689349e+19)
- XMM5: 612F6F666E697265 747465622E6E6F74 (2.0226296e+20 | 1.8062075e+28 | 7.7452192e+31 | 5.4213925e-11)
- XMM6: 0000000000000000 0000000000000000 (0 | 0 | 0 | 0)
- XMM7: 0000000000000000 0000000000000000 (0 | 0 | 0 | 0)
- AF: 0 | CF: 0 | DF: 0 
- IF: 1 | OF: 0 | PF: 1 
- SF: 0 | TF: 0 | ZF: 1 

== Installed Mods ==
x | [v1.0.4] absolllute.installer
x | [v8.0.1-alpha.7] absolllute.megahack
x | [v1.4.6] alphalaneous.happy_textures
x | [v1.0.1] alphalaneous.settings_everywhere
x | [v1.1.2] bitz.customprofiles
x | [v1.0.7] cdc.level_thumbnails
x | [v2.2.0] cgytrus.smooth-particles
x | [v4.2.8] cvolton.betterinfo
x | [v1.0.1] cvolton.level-id-api
x | [v1.2.1] cvolton.misc_bugfixes
x | [v1.6.2] dankmeme.globed2
x | [v1.0.9] firee.goldenbest
x | [v0.3.1] flafy.autonong
x | [v2.11.0] fleym.nongd
x | [v1.7.1] geode.custom-keybinds
x | [v3.4.0] geode.loader
x | [v1.13.2] geode.node-ids
x | [v1.2.4] hiimjustin000.demons_in_between
x | [v1.1.0] hjfod.backups
x | [v6.7.0] hjfod.betteredit
x | [v1.3.0] hjfod.gdshare
x | [v1.2.1] hjfod.gmd-api
x | [v1.0.0] hjfod.trashcan
x | [v1.0.3] iswilljr.enter-search
x | [v1.2.0] itzkiba.grandpa_demon
x | [v1.0.7] jouca.badgesapi
x | [v1.0.0] m336.autoleaderboard
x | [v1.3.7] m336.levelinfo
x | [v1.1.0] m336.modbadgeinfo
x | [v1.2.1] mat.run-info
x | [v1.0.0-beta.41] minemaker0430.gddp_integration
x | [v1.2.1] omgrod.geodify
x | [v1.6.0] prevter.bettercrash
x | [v1.3.2] raydeeux_thesillydoggo.evenmoreleveltags
x | [v1.1.6] rynat.better_unlock_info
x | [v4.2.0-beta.1] spaghettdev.betterinputs
  | [v1.1.21] syzzi.click_between_frames
x | [v1.1.0] techstudent10.settings_plus
x | [v1.0.1] uproxide.animated_fire
x | [v1.1.0] xanii.youtubers
  | [v1.2.0-beta.1] zmx.cbf-lite

== Stack Allocations ==
- 0x304E93D870: 1D77DB31700 (&"")
- 0x304E93D878: 7FF92F24A1C0 (-> 0x7FF92F16E9A0 -> libcocos2d.dll+0xE9A0 (cocos2d::CCCopying::copyWithZone+0x0))
- 0x304E93D880: 1D73725EAA0 (-> 0x7FF92F24A1C0 -> 0x7FF92F16E9A0 -> libcocos2d.dll+0xE9A0 (cocos2d::CCCopying::copyWithZone+0x0))
- 0x304E93D888: 1D77E19E720 (-> 0x1D77E25FEE0 -> 0x1D77E25FF10 -> 0x1D77E25FEE0 -> 0x1D77E25FF10 -> 0x1D77E25FEE0 -> 0x1D77E25FF10 -> 0x1D77E25FEE0 -> 0x1D77E25FF10 -> 0x1D77E25FEE0 -> 0x1D77E25FF10 -> 0x1D77E25FEE0 -> 0x1D77E25FF10 [...])
- 0x304E93D890: 1D700000000 (&"")
- 0x304E93D898: 1D76D88A200 (-> 0x1D76D880ED0 -> 0x17830004)
- 0x304E93D8A0: 00000026 (38i | 38u)
- 0x304E93D8A8: 4284000044074000 (4792955904570376192i | 1141325824u)
- 0x304E93D8B0: 1D76D8802A8 (-> 0x102000301010002)
- 0x304E93D8B8: 00000020 (32i | 32u)
- 0x304E93D8C0: 1D700000002 (&"")
- 0x304E93D8C8: 304EB6E000 (&"")
- 0x304E93D8D0: C0002422C0000 (3377709420642304i | 1110179840u)
- 0x304E93D8D8: 7FF9E6AA4B4D (ntdll.dll+0x54B4D (RtlGetExtendedContextLength2+0x3d))
- 0x304E93D8E0: 00000000 (0i | 0u)
- 0x304E93D8E8: 304E93DB80 (-> 0x1D76D780150 -> 0x1D7403BFC80 -> 0x1D71742CD90 -> 0x1D7409DD060 -> 0x1D73788D030 -> 0x1D74032E080 -> 0x1D71BD61C80 -> 0x1D732600FF0 -> 0x1D71B9E23B0 -> 0x1D71B8AA850 -> 0x1D732B2E770 -> 0x1D77D998F10 [...])
- 0x304E93D8F0: 1D73725AD00 (-> 0x7FF92F24A1C0 -> 0x7FF92F16E9A0 -> libcocos2d.dll+0xE9A0 (cocos2d::CCCopying::copyWithZone+0x0))
- 0x304E93D8F8: 1D74062CC60 (-> 0x7FF92F2616E0 -> 0x7FF92F16E9A0 -> libcocos2d.dll+0xE9A0 (cocos2d::CCCopying::copyWithZone+0x0))
- 0x304E93D900: 100000010 (4294967312i | 16u)
- 0x304E93D908: 1D732DFC3E0 (&"")
- 0x304E93D910: 00000000 (0i | 0u)
- 0x304E93D918: 00010040 (65600i | 65600u)
- 0x304E93D920: 00000708 (1800i | 1800u)
- 0x304E93D928: 7FF9E6A6E6CF (ntdll.dll+0x1E6CF (<0x1e57a>+0x155))
- 0x304E93D930: 00000000 (0i | 0u)
- 0x304E93D938: 304E93DB80 (-> 0x1D76D780150 -> 0x1D7403BFC80 -> 0x1D71742CD90 -> 0x1D7409DD060 -> 0x1D73788D030 -> 0x1D74032E080 -> 0x1D71BD61C80 -> 0x1D732600FF0 -> 0x1D71B9E23B0 -> 0x1D71B8AA850 -> 0x1D732B2E770 -> 0x1D77D998F10 [...])
- 0x304E93D940: 3F80000080000000 (4575657223555907584i | 2147483648u)
- 0x304E93D948: 7FF9000004D0 (absolllute.megahack.dll+0x16F04D0)
- 0x304E93D950: 00000000 (0i | 0u)
- 0x304E93D958: 1D76D888040 (-> 0x1D76D880ED0 -> 0x17880004)
- 0x304E93D960: 4F0FFFFFB30 (5433133628208i | 4294966064u)
- 0x304E93D968: 4D0FFFFFB30 (5295694674736i | 4294966064u)
- 0x304E93D970: 00000021 (33i | 33u)
- 0x304E93D978: 00000040 (64i | 64u)
- 0x304E93D980: 1D76D880ED0 (-> 0x17880004)
- 0x304E93D988: 1D700000088 (&"")
- 0x304E93D990: 3F999900 (1067030784i | 1067030784u)
- 0x304E93D998: 7FF9E6BDEBF8 (&"")
- 0x304E93D9A0: 304E93FA70 (&"")
- 0x304E93D9A8: 7FF9E6ADF5D0 (ntdll.dll+0x8F5D0 (_C_specific_handler+0x0))
- 0x304E93D9B0: 7FF9E6BB2BC8 (-> 0x5AF0700000001)
- 0x304E93D9B8: 7FF9E6AAAF28 (ntdll.dll+0x5AF28 (RtlUserThreadStart+0x28))
- 0x304E93D9C0: 304E93DA50 (-> 0xC)
- 0x304E93D9C8: 7FF9E6A50000 (-> 0x300905A4D)
- 0x304E93D9D0: 304E940000 (207476752384i | 1318322176u)
- 0x304E93D9D8: 304E919000 (&"")
- 0x304E93D9E0: 7FF9E6AAAF28 (ntdll.dll+0x5AF28 (RtlUserThreadStart+0x28))
- 0x304E93D9E8: 7FF9E6A50000 (-> 0x300905A4D)
- 0x304E93D9F0: 7FF9E6BDEBF8 (&"")
- 0x304E93D9F8: 304E93FA70 (&"")
- 0x304E93DA00: 1D731FCD68F (-> 0x7030000000090)
- 0x304E93DA08: 304E93D490 (&"")
- 0x304E93DA10: 7FF9E6ADF5D0 (ntdll.dll+0x8F5D0 (_C_specific_handler+0x0))
- 0x304E93DA18: 7FF9E6BB2BC8 (-> 0x5AF0700000001)
- 0x304E93DA20: 304E93DA50 (-> 0xC)
- 0x304E93DA28: 00000000 (0i | 0u)
- 0x304E93DA30: 00000000 (0i | 0u)
- 0x304E93DA38: 00000000 (0i | 0u)
- 0x304E93DA40: 00000000 (0i | 0u)
- 0x304E93DA48: 00000000 (0i | 0u)
- 0x304E93DA50: 0000000C (12i | 12u)
- 0x304E93DA58: 1D770C63800 (0x1D770C63800 (Hook Handler))
- 0x304E93DA60: 7FF93DC26600 (jouca.badgesapi.dll+0x6600 (<0x6600>+0x0))
- 0x304E93DA68: 7FF93DC20000 (&"MZx")
- 0x304E93DA70: 7FF93DC4F504 (-> 0x6600000060F0)
- 0x304E93DA78: 7FF93DC20000 (&"MZx")
- 0x304E93DA80: 7FF93DC4F444 (-> 0x5B33000054F0)
- 0x304E93DA88: 1D771090000 (0x1D771090000 (Hook Handler))
- 0x304E93DA90: 1D7710944B0 (&"")
- 0x304E93DA98: 7FF6DEFA0000 (-> 0x300905A4D)
- 0x304E93DAA0: 7FF6DF63BD88 (&" !:")
- 0x304E93DAA8: 1D770C60000 (0x1D770C60000 (Hook Handler))
- 0x304E93DAB0: 1D770C638B0 (&"")
- 0x304E93DAB8: 7FF92DAD0000 (&"MZx")
- 0x304E93DAC0: 7FF92E6AADA4 (-> 0x3600B70035FFF0)
- 0x304E93DAC8: 1D770C60000 (0x1D770C60000 (Hook Handler))
- 0x304E93DAD0: 1D770C638B0 (&"")
- 0x304E93DAD8: 7FF6DEFA0000 (-> 0x300905A4D)
- 0x304E93DAE0: 7FF6DF62F968 (&"")
- 0x304E93DAE8: 7FF6DEFA0000 (-> 0x300905A4D)
- 0x304E93DAF0: 7FF6DF62F4AC (-> 0x13F6A80013E4C0)
- 0x304E93DAF8: 7FF6DEFA0000 (-> 0x300905A4D)
- 0x304E93DB00: 7FF6DF62F4A0 (-> 0x13E4B50013E3D0)
- 0x304E93DB08: 1D771200000 (0x1D771200000 (Hook Handler))
- 0x304E93DB10: 1D77120B8B0 (&"")
- 0x304E93DB18: 7FF92ADD0000 (&"MZx")
- 0x304E93DB20: 7FF92AF86F3C (-> 0xF3F76000F3EB0)
- 0x304E93DB28: 1D732B1AAD0 (-> 0x1D71B80DB20 -> 0x1D770AF8140 -> 0x1D7736FDFE0 -> 0x1D770AF8140 -> 0x1D7736FDFE0 -> 0x1D770AF8140 -> 0x1D7736FDFE0 -> 0x1D770AF8140 -> 0x1D7736FDFE0 -> 0x1D770AF8140 -> 0x1D7736FDFE0 -> 0x1D770AF8140 [...])
- 0x304E93DB30: 14EC04785B2A (23003919833898i | 74996522u)
- 0x304E93DB38: 7FF9E6A8AFF1 (ntdll.dll+0x3AFF1 (RtlFreeHeap+0x51))
- 0x304E93DB40: 1D732A8C340 (-> 0x7FF92F244210 -> 0x7FF92F1667F0 -> libcocos2d.dll+0x67F0 (cocos2d::CCArray::copyWithZone+0x0))
- 0x304E93DB48: 1D73725AD00 (-> 0x7FF92F24A1C0 -> 0x7FF92F16E9A0 -> libcocos2d.dll+0xE9A0 (cocos2d::CCCopying::copyWithZone+0x0))
- 0x304E93DB50: 1D74062CC60 (-> 0x7FF92F2616E0 -> 0x7FF92F16E9A0 -> libcocos2d.dll+0xE9A0 (cocos2d::CCCopying::copyWithZone+0x0))
- 0x304E93DB58: 00000002 (2i | 2u)
- 0x304E93DB60: 1D732DFC3E0 (&"")
- 0x304E93DB68: 1D731FCDF20 (&"")
- 0x304E93DB70: 304E93E310 (-> 0x3B888889)
- 0x304E93DB78: 7FF9E6AF403E (ntdll.dll+0xA403E (KiUserExceptionDispatcher+0x2e))
- 0x304E93DB80: 1D76D780150 (-> 0x1D7403BFC80 -> 0x1D71742CD90 -> 0x1D7409DD060 -> 0x1D73788D030 -> 0x1D74032E080 -> 0x1D71BD61C80 -> 0x1D732600FF0 -> 0x1D71B9E23B0 -> 0x1D71B8AA850 -> 0x1D732B2E770 -> 0x1D77D998F10 -> 0x1D732134260 [...])
- 0x304E93DB88: 304E93DD60 (&"")
- 0x304E93DB90: 1D732DFC090 (-> 0x7FF6DF536390 -> 0x7FF6DF442DBA -> GeometryDash.exe+0x4A2DBA (<0x4a2ca6>+0x114))
- 0x304E93DB98: 1D731E60000 (&"")
- 0x304E93DBA0: 00000015 (21i | 21u)
- 0x304E93DBA8: 7FF92C5E5144 (alphalaneous.happy_textures.dll+0x45144)
- 0x304E93DBB0: 1FA70010005F (34802121048159i | 1048671u)
- 0x304E93DBB8: 53002B002B0033 (23362607753396275i | 2818099u)
- 0x304E93DBC0: 10246002B002B (283974650495019i | 2818091u)
- 0x304E93DBC8: 00000000 (0i | 0u)
- 0x304E93DBD0: 00000000 (0i | 0u)
- 0x304E93DBD8: 00000000 (0i | 0u)
- 0x304E93DBE0: 00000000 (0i | 0u)
- 0x304E93DBE8: 00000000 (0i | 0u)
- 0x304E93DBF0: 00000000 (0i | 0u)
- 0x304E93DBF8: 00000000 (0i | 0u)
- 0x304E93DC00: 00000000 (0i | 0u)
- 0x304E93DC08: 00000000 (0i | 0u)
- 0x304E93DC10: 00000000 (0i | 0u)
- 0x304E93DC18: 304E93FA70 (&"")
- 0x304E93DC20: 00000000 (0i | 0u)
- 0x304E93DC28: 00000000 (0i | 0u)
- 0x304E93DC30: 00000000 (0i | 0u)
- 0x304E93DC38: 1D76D8821C0 (-> 0x1D76D880ED0 -> 0x17950002)
- 0x304E93DC40: 00000001 (1i | 1u)
- 0x304E93DC48: 00000003 (3i | 3u)
- 0x304E93DC50: 304E93E090 (&"")
- 0x304E93DC58: 00000000 (0i | 0u)
- 0x304E93DC60: 00000000 (0i | 0u)
- 0x304E93DC68: 00000000 (0i | 0u)

== Hardware Information ==
- CPU: Intel(R) Core(TM) i7-14700KF (20 cores, 28 threads)
- GPU: NVIDIA GeForce RTX 4060 Ti
- RAM: 32581 MB total, 19233 MB used, 13348 MB free
- SWAP: 32768 MB total, 12099 MB used, 20669 MB free
- OS: Windows 11 amd64 (v.10.0.22621.3672)
```

**Comment by Jouca** [comment]
I've heard on Discord that your problem has been resolved, is it still the case?

**Comment by banana-man95** [comment]
I myself have not mentioned this problem on Discord, all I've done is just made this issue on GitHub. This problem has not been resolved btw, crash still happens :(

**Comment by Jouca** [comment]
Could you please provide me back the new logs you got?

**Comment by banana-man95** [comment]
Here's a log I just made a few minutes ago:

```
2024-09-15T20:15:03-0400
Error 404: Fun not found.

== Geode Information ==
- Working Directory: C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash
- Loader Version: v3.6.1 (Geometry Dash v2.206)
- Loader Commit: 00e0600
- Bindings Commit: fd1495d
- Installed Mods: 42 (Loaded: 39/39)
- Problems: 0

== Exception Information ==
- Thread Information: "Main" (ID: 30408)
- Thread Start Address: GeometryDash.exe+0x4A41C8 (<0x4a41c8>+0x0)
- Exception Code: EXCEPTION_ACCESS_VIOLATION (0xC0000005)
- Exception Address: 0x0840C748
- Exception Flags: 0x0
- Exception Parameters: 0x8, 0x840C748
- Access Violation Type: DEP
- Access Violation Address: 0x840C748

== Stack Trace ==
- 0x0840C748
- jouca.badgesapi.dll+0x9CA0 (<0x9b20>+0x180)
- jouca.badgesapi.dll+0x9734 (<0x8940>+0xdf4)
- 0x1F5BECC4C72+0x0
- GeometryDash.exe+0x3A21A2 (ProfilePage::onRequests+0xb2)
- 0x1F5BE893872+0x0
- Geode.dll+0x3C06FE (ProfilePage::getUserInfoFinished+0x3e)
└ /home/runner/work/geode/geode/build/bindings/bindings/Geode/GeneratedSource.cpp:28990
- 0x1F5BE893872+0x0
- GeometryDash.exe+0x154352 (<0x154200>+0x152)
- GeometryDash.exe+0x13EAF0 (GameLevelManager::handleIt+0x630)
- GeometryDash.exe+0x13E484 (GameLevelManager::ProcessHttpRequest+0x254)
- 0x1F5BECFBC72+0x0
- cvolton.betterinfo.dll+0xF3F00
- cvolton.betterinfo.dll+0x26417 (<0x25b90>+0x887)
- 0x1F5BECFBC72+0x0
- libExtensions.dll+0x1805A (cocos2d::extension::CCHttpClient::dispatchResponseCallbacks+0xaa)
- libcocos2d.dll+0xC0629 (cocos2d::CCTimer::update+0x69)
- libcocos2d.dll+0xC049B (cocos2d::CCScheduler::update+0x10b)
- 0x1F5BE894472+0x0
- 0x1F5BE894472+0x0
- 0x1F5BE894472+0x0
- 0x1F5BE894472+0x0
- absolllute.megahack.dll+0x164B15 (<0x164aa0>+0x75)
- 0x1F5CDDB28D2+0x0
- libcocos2d.dll+0xBC33B (<0xbc2c0>+0x7b)
- libcocos2d.dll+0x72CD2 (cocos2d::CCApplication::run+0x462)
- GeometryDash.exe+0x4A2D69 (<0x4a2ca6>+0xc3)
- Geode.dll+0x28E54A (gdMainHook+0x22a)
└ /home/runner/work/geode/geode/loader/src/platform/windows/main.cpp:181
- GeometryDash.exe+0x4A415A (__scrt_common_main_seh+0x106)
- KERNEL32.DLL+0x1257D (BaseThreadInitThunk+0x1d)
- ntdll.dll+0x5AF28 (RtlUserThreadStart+0x28)

== Register States ==
- RAX: 7FFD75C916E0 (-> 0x7FFD75B9E9A0 -> libcocos2d.dll+0xE9A0 (cocos2d::CCCopying::copyWithZone+0x0))
- RBX: 00000000 (0i | 0u)
- RCX: 7FFD75C916E0 (-> 0x7FFD75B9E9A0 -> libcocos2d.dll+0xE9A0 (cocos2d::CCCopying::copyWithZone+0x0))
- RDX: 7FFD75B9E9A0 (libcocos2d.dll+0xE9A0 (cocos2d::CCCopying::copyWithZone+0x0))
- RBP: 00000000 (0i | 0u)
- RSP: 42522FF970 (&"")
- RDI: 00000000 (0i | 0u)
- RSI: 00000000 (0i | 0u)
- R8: 1F5BB391F80 (&"")
- R9: 00000001 (1i | 1u)
- R10: 00000003 (3i | 3u)
- R11: 42522FE000 (&"")
- R12: 00000000 (0i | 0u)
- R13: 00000000 (0i | 0u)
- R14: 00000000 (0i | 0u)
- R15: 00000000 (0i | 0u)
- RIP: 7FFDC866AF28 (ntdll.dll+0x5AF28 (RtlUserThreadStart+0x28))
- XMM0: 0000000000000000 0000000000000000 (0 | 0 | 0 | 0)
- XMM1: 676150656C69666F 7250207373616C63 (1.0640155e+24 | 1.1286538e+27 | 4.122375e+30 | 1.7859881e+31)
- XMM2: 65676150656C6966 6F7250207373616C (6.829136e+22 | 6.977642e+22 | 7.4992238e+28 | 1.9282594e+31)
- XMM3: 0000000000000000 40444999A0000000 (0 | 0 | 3.066992 | -1.0842022e-19)
- XMM4: 0000000000000000 4013CCCCE0000000 (0 | 0 | 2.3093748 | -3.689349e+19)
- XMM5: 612F6F666E697265 747465622E6E6F74 (2.0226296e+20 | 1.8062075e+28 | 7.7452192e+31 | 5.4213925e-11)
- XMM6: 0000000000000000 0000000000000000 (0 | 0 | 0 | 0)
- XMM7: 0000000000000000 0000000000000000 (0 | 0 | 0 | 0)
- AF: 0 | CF: 0 | DF: 0 
- IF: 1 | OF: 0 | PF: 0 
- SF: 0 | TF: 0 | ZF: 0 

== Installed Mods ==
x | [v1.0.4] absolllute.installer
x | [v8.0.1-alpha.7] absolllute.megahack
x | [v1.4.10] alphalaneous.happy_textures
x | [v1.0.1] alphalaneous.settings_everywhere
x | [v1.1.2] bitz.customprofiles
x | [v1.0.7] cdc.level_thumbnails
x | [v2.2.0] cgytrus.smooth-particles
x | [v4.2.8] cvolton.betterinfo
x | [v1.0.1] cvolton.level-id-api
x | [v1.2.1] cvolton.misc_bugfixes
x | [v1.6.2] dankmeme.globed2
x | [v1.0.9] firee.goldenbest
x | [v0.3.2] flafy.autonong
x | [v2.11.0] fleym.nongd
x | [v1.9.0] geode.custom-keybinds
x | [v3.6.1] geode.loader
x | [v1.14.0] geode.node-ids
x | [v1.2.4] hiimjustin000.demons_in_between
x | [v1.1.0] hjfod.backups
x | [v6.7.0] hjfod.betteredit
x | [v1.3.0] hjfod.gdshare
x | [v1.2.1] hjfod.gmd-api
x | [v1.0.0] hjfod.trashcan
x | [v1.0.3] iswilljr.enter-search
x | [v1.2.0] itzkiba.grandpa_demon
x | [v1.1.0] jouca.badgesapi
x | [v1.0.0] m336.autoleaderboard
x | [v1.3.7] m336.levelinfo
x | [v1.1.0] m336.modbadgeinfo
x | [v1.2.1] mat.run-info
x | [v1.0.0-beta.42] minemaker0430.gddp_integration
x | [v1.2.1] omgrod.geodify
x | [v1.6.0] prevter.bettercrash
x | [v1.3.2] raydeeux_thesillydoggo.evenmoreleveltags
x | [v1.1.6] rynat.better_unlock_info
x | [v4.2.0-beta.1] spaghettdev.betterinputs
  | [v1.1.21] syzzi.click_between_frames
x | [v1.1.0] techstudent10.settings_plus
  | [v4.6.8] tobyadd.gdh
x | [v1.0.1] uproxide.animated_fire
x | [v1.1.0] xanii.youtubers
  | [v1.2.0-beta.1] zmx.cbf-lite

== Stack Allocations ==
- 0x42522FD770: 034D0093 (55378067i | 55378067u)
- 0x42522FD778: 00000020 (32i | 32u)
- 0x42522FD780: 1F5CC6BA6B0 (-> 0x1F5BB398040 -> &"")
- 0x42522FD788: 7FFD75C7A1C0 (-> 0x7FFD75B9E9A0 -> libcocos2d.dll+0xE9A0 (cocos2d::CCCopying::copyWithZone+0x0))
- 0x42522FD790: 1F581CB3BC0 (-> 0x7FFD75C7A1C0 -> 0x7FFD75B9E9A0 -> libcocos2d.dll+0xE9A0 (cocos2d::CCCopying::copyWithZone+0x0))
- 0x42522FD798: 1F5CCBB5460 (-> 0x1F5BEAE2D70 -> 0x1F5BEAE3430 -> 0x1F5BEAE2D70 -> 0x1F5BEAE3430 -> 0x1F5BEAE2D70 -> 0x1F5BEAE3430 -> 0x1F5BEAE2D70 -> 0x1F5BEAE3430 -> 0x1F5BEAE2D70 -> 0x1F5BEAE3430 -> 0x1F5BEAE2D70 -> 0x1F5BEAE3430 [...])
- 0x42522FD7A0: 1F500000000 (2151778615296i | 0u)
- 0x42522FD7A8: 1F5BB398040 (&"")
- 0x42522FD7B0: 00000026 (38i | 38u)
- 0x42522FD7B8: 4284000044074000 (4792955904570376192i | 1141325824u)
- 0x42522FD7C0: 1F500000002 (2151778615298i | 2u)
- 0x42522FD7C8: 42521E6000 (&"")
- 0x42522FD7D0: 1F5BB390F00 (-> 0xF15001C)
- 0x42522FD7D8: 7FFDC8664B4D (ntdll.dll+0x54B4D (RtlGetExtendedContextLength2+0x3d))
- 0x42522FD7E0: C0002422C0000 (3377709420642304i | 1110179840u)
- 0x42522FD7E8: 42522FDA80 (-> 0x1F58FCC4260 -> 0x1F5BB3B34C0 -> &"")
- 0x42522FD7F0: 1F590B13380 (-> 0x7FFD75C7A1C0 -> 0x7FFD75B9E9A0 -> libcocos2d.dll+0xE9A0 (cocos2d::CCCopying::copyWithZone+0x0))
- 0x42522FD7F8: 1F616730C70 (-> 0x7FFD75C916E0 -> 0x7FFD75B9E9A0 -> libcocos2d.dll+0xE9A0 (cocos2d::CCCopying::copyWithZone+0x0))
- 0x42522FD800: 100000010 (4294967312i | 16u)
- 0x42522FD808: 1F594002E10 (&"")
- 0x42522FD810: 00000000 (0i | 0u)
- 0x42522FD818: 00010040 (65600i | 65600u)
- 0x42522FD820: 00000718 (1816i | 1816u)
- 0x42522FD828: 7FFDC862E6CF (ntdll.dll+0x1E6CF (<0x1e57a>+0x155))
- 0x42522FD830: 00000000 (0i | 0u)
- 0x42522FD838: 42522FDA80 (-> 0x1F58FCC4260 -> 0x1F5BB3B34C0 -> &"")
- 0x42522FD840: 1F582A11B00 (&"")
- 0x42522FD848: 000004D0 (1232i | 1232u)
- 0x42522FD850: 3F80000080000000 (4575657223555907584i | 2147483648u)
- 0x42522FD858: 7FFDC864C350 (ntdll.dll+0x3C350 (<0x3bb60>+0x7f0))
- 0x42522FD860: 4F0FFFFFB30 (5433133628208i | 4294966064u)
- 0x42522FD868: 4D0FFFFFB30 (5295694674736i | 4294966064u)
- 0x42522FD870: 00000021 (33i | 33u)
- 0x42522FD878: 00000000 (0i | 0u)
- 0x42522FD880: 1F5BB3902B0 (-> 0x104000501030004)
- 0x42522FD888: 00000040 (64i | 64u)
- 0x42522FD890: 1F5BB390F00 (-> 0xF15001A)
- 0x42522FD898: 7FFDC879EBF8 (&"")
- 0x42522FD8A0: 42522FF970 (&"")
- 0x42522FD8A8: 7FFDC869F5D0 (ntdll.dll+0x8F5D0 (_C_specific_handler+0x0))
- 0x42522FD8B0: 7FFDC8772BC8 (-> 0x5AF0700000001)
- 0x42522FD8B8: 7FFDC866AF28 (ntdll.dll+0x5AF28 (RtlUserThreadStart+0x28))
- 0x42522FD8C0: 42522FD950 (-> 0xC)
- 0x42522FD8C8: 7FFDC8610000 (-> 0x300905A4D)
- 0x42522FD8D0: 4252300000 (284846718976i | 1378877440u)
- 0x42522FD8D8: 42522D8000 (&"")
- 0x42522FD8E0: 7FFDC866AF28 (ntdll.dll+0x5AF28 (RtlUserThreadStart+0x28))
- 0x42522FD8E8: 7FFDC8610000 (-> 0x300905A4D)
- 0x42522FD8F0: 7FFDC879EBF8 (&"")
- 0x42522FD8F8: 42522FF970 (&"")
- 0x42522FD900: 00000030 (48i | 48u)
- 0x42522FD908: 42522FD390 (&"")
- 0x42522FD910: 7FFDC869F5D0 (ntdll.dll+0x8F5D0 (_C_specific_handler+0x0))
- 0x42522FD918: 7FFDC8772BC8 (-> 0x5AF0700000001)
- 0x42522FD920: 42522FD950 (-> 0xC)
- 0x42522FD928: 1F500000000 (2151778615296i | 0u)
- 0x42522FD930: 00000000 (0i | 0u)
- 0x42522FD938: 00000000 (0i | 0u)
- 0x42522FD940: 00000000 (0i | 0u)
- 0x42522FD948: 7FFDC864C350 (ntdll.dll+0x3C350 (<0x3bb60>+0x7f0))
- 0x42522FD950: 0000000C (12i | 12u)
- 0x42522FD958: 1F5BE893800 (0x1F5BE893800 (Hook Handler))
- 0x42522FD960: 7FFD19D3A0A0 (jouca.badgesapi.dll+0xA0A0 (<0xa0a0>+0x0))
- 0x42522FD968: 7FFD19D30000 (&"MZx")
- 0x42522FD970: 7FFD19D64900 (-> 0xA0A000009B90)
- 0x42522FD978: 7FFD19D30000 (&"MZx")
- 0x42522FD980: 7FFD19D64888 (-> 0x98D300009320)
- 0x42522FD988: 1F5BECC0000 (0x1F5BECC0000 (Hook Handler))
- 0x42522FD990: 1F5BECC4CB0 (&"")
- 0x42522FD998: 7FF7DF0A0000 (-> 0x300905A4D)
- 0x42522FD9A0: 7FF7DF73BD88 (&" !:")
- 0x42522FD9A8: 1F5BE890000 (0x1F5BE890000 (Hook Handler))
- 0x42522FD9B0: 1F5BE8938B0 (&"")
- 0x42522FD9B8: 7FFD103C0000 (&"MZx")
- 0x42522FD9C0: 7FFD11057F88 (-> 0x3C0787003C06C0)
- 0x42522FD9C8: 1F5BE890000 (0x1F5BE890000 (Hook Handler))
- 0x42522FD9D0: 1F5BE8938B0 (&"")
- 0x42522FD9D8: 7FF7DF0A0000 (-> 0x300905A4D)
- 0x42522FD9E0: 7FF7DF72F968 (&"")
- 0x42522FD9E8: 7FF7DF0A0000 (-> 0x300905A4D)
- 0x42522FD9F0: 7FF7DF72F4AC (-> 0x13F6A80013E4C0)
- 0x42522FD9F8: 7FF7DF0A0000 (-> 0x300905A4D)
- 0x42522FDA00: 7FF7DF72F4A0 (-> 0x13E4B50013E3D0)
- 0x42522FDA08: 1F5BECF0000 (0x1F5BECF0000 (Hook Handler))
- 0x42522FDA10: 1F5BECFBCB0 (&"")
- 0x42522FDA18: 7FFD101F0000 (&"MZx")
- 0x42522FDA20: 7FFD103A6F3C (-> 0xF3F76000F3EB0)
- 0x42522FDA28: 1F614CEE250 (&"libssl-3-x64.dll")
- 0x42522FDA30: C6F594F53522 (218758068385058i | 2499097890u)
- 0x42522FDA38: 1F582B606E0 (-> 0x1F5E7902E90 -> 0x1F5BE764270 -> 0x1F5CC5B0E60 -> 0x1F5BE764270 -> 0x1F5CC5B0E60 -> 0x1F5BE764270 -> 0x1F5CC5B0E60 -> 0x1F5BE764270 -> 0x1F5CC5B0E60 -> 0x1F5BE764270 -> 0x1F5CC5B0E60 -> 0x1F5BE764270 [...])
- 0x42522FDA40: 1F58272EC10 (-> 0x7FFD75C74210 -> 0x7FFD75B967F0 -> libcocos2d.dll+0x67F0 (cocos2d::CCArray::copyWithZone+0x0))
- 0x42522FDA48: 1F590B13380 (-> 0x7FFD75C7A1C0 -> 0x7FFD75B9E9A0 -> libcocos2d.dll+0xE9A0 (cocos2d::CCCopying::copyWithZone+0x0))
- 0x42522FDA50: 1F616730C70 (-> 0x7FFD75C916E0 -> 0x7FFD75B9E9A0 -> libcocos2d.dll+0xE9A0 (cocos2d::CCCopying::copyWithZone+0x0))
- 0x42522FDA58: 00000002 (2i | 2u)
- 0x42522FDA60: 1F594002E10 (&"")
- 0x42522FDA68: 1F5CCF4F530 (&"")
- 0x42522FDA70: 42522FE220 (-> 0x3B888889)
- 0x42522FDA78: 7FFDC86B403E (ntdll.dll+0xA403E (KiUserExceptionDispatcher+0x2e))
- 0x42522FDA80: 1F58FCC4260 (-> 0x1F5BB3B34C0 -> &"")
- 0x42522FDA88: 7FFDC5F0364B (ucrtbase.dll+0x1364B (free_base+0x1b))
- 0x42522FDA90: 1F594002AC0 (-> 0x7FF7DF636390 -> 0x7FF7DF542DBA -> GeometryDash.exe+0x4A2DBA (<0x4a2ca6>+0x114))
- 0x42522FDA98: 42522FDC70 (&"ton.betterinfo/a")
- 0x42522FDAA0: 1F500000000 (2151778615296i | 0u)
- 0x42522FDAA8: 1F5BB3B34C0 (&"")
- 0x42522FDAB0: 1FB70010005F (34870840524895i | 1048671u)
- 0x42522FDAB8: 53002B002B0033 (23362607753396275i | 2818099u)
- 0x42522FDAC0: 10202002B002B (283682592718891i | 2818091u)
- 0x42522FDAC8: 00000000 (0i | 0u)
- 0x42522FDAD0: 00000000 (0i | 0u)
- 0x42522FDAD8: 00000000 (0i | 0u)
- 0x42522FDAE0: 00000000 (0i | 0u)
- 0x42522FDAE8: 00000000 (0i | 0u)
- 0x42522FDAF0: 00000000 (0i | 0u)
- 0x42522FDAF8: 7FFD75C916E0 (-> 0x7FFD75B9E9A0 -> libcocos2d.dll+0xE9A0 (cocos2d::CCCopying::copyWithZone+0x0))
- 0x42522FDB00: 7FFD75C916E0 (-> 0x7FFD75B9E9A0 -> libcocos2d.dll+0xE9A0 (cocos2d::CCCopying::copyWithZone+0x0))
- 0x42522FDB08: 7FFD75B9E9A0 (libcocos2d.dll+0xE9A0 (cocos2d::CCCopying::copyWithZone+0x0))
- 0x42522FDB10: 00000000 (0i | 0u)
- 0x42522FDB18: 42522FF970 (&"")
- 0x42522FDB20: 00000000 (0i | 0u)
- 0x42522FDB28: 00000000 (0i | 0u)
- 0x42522FDB30: 00000000 (0i | 0u)
- 0x42522FDB38: 1F5BB391F80 (&"")
- 0x42522FDB40: 00000001 (1i | 1u)
- 0x42522FDB48: 00000003 (3i | 3u)
- 0x42522FDB50: 42522FE000 (&"")
- 0x42522FDB58: 00000000 (0i | 0u)
- 0x42522FDB60: 00000000 (0i | 0u)
- 0x42522FDB68: 00000000 (0i | 0u)

== Hardware Information ==
- CPU: Intel(R) Core(TM) i7-14700KF (20 cores, 28 threads)
- GPU: NVIDIA GeForce RTX 4060 Ti
- RAM: 32581 MB total, 15143 MB used, 17438 MB free
- SWAP: 32768 MB total, 9160 MB used, 23608 MB free
- OS: Windows 11 amd64 (v.10.0.22621.3958)
```

**Comment by Jouca** [comment]
Can you try disabling m336.modbadgeinfo ?

**Comment by banana-man95** [comment]
That causes the crash to not happen, so it seems the two mods are conflicting?

**Comment by Jouca** [comment]
Seems to be the issue ye, but pretty sure modbadgeinfo might do something wrong, will close it because it's not really Badges API related
